"""
AutoSRE — Planner Agent
The orchestrator. Receives a normalized incident, produces a JSON execution plan,
dispatches subtasks, tracks completion, and makes resolution decisions.
"""

import json
import logging
import uuid
from typing import Any, Dict, List

from agents.base import BaseAgent
from memory.vector_store import get_vector_store

logger = logging.getLogger("autosre.agents.planner")

PLANNER_SYSTEM_PROMPT = """You are the Planner Agent for AutoSRE, an autonomous incident resolution system.

Your role:
1. Receive an incident event and decompose it into subtasks
2. Assign each subtask to the appropriate specialist agent
3. Define task dependencies (which tasks must complete before others)
4. Produce a structured JSON execution plan

Available specialist agents:
- analyst: Reads logs, metrics, and stack traces. Produces root cause diagnosis.
- researcher: Searches web and runbooks for similar incidents and known fixes.
- coder: Writes and runs diagnostic scripts, health checks, or postmortem templates.
- communicator: Posts incident updates to Slack with structured formatting.
- executor: Creates GitHub issues, Jira tickets, and triggers rollbacks.

Response format — you MUST return a JSON object like this:
{
    "incident_id": "INC-XXXX",
    "severity": "critical|high|medium|low",
    "initial_assessment": "Brief assessment of the incident",
    "tasks": [
        {"id": "t1", "agent": "analyst", "input": "description of what to analyze", "depends_on": []},
        {"id": "t2", "agent": "researcher", "input": "what to research", "depends_on": []},
        {"id": "t3", "agent": "executor", "input": "what action to take", "depends_on": ["t1", "t2"]},
        {"id": "t4", "agent": "communicator", "input": "what to communicate", "depends_on": ["t1"]}
    ],
    "reasoning": "Explain your task decomposition logic"
}

Rules:
- Always include at least analyst and communicator tasks
- Tasks with no dependencies run in parallel
- Keep the plan focused and actionable
- For critical/high severity: include executor tasks for GitHub issue creation
"""


class PlannerAgent(BaseAgent):
    """The Planner Agent — orchestrates the incident resolution workflow."""

    def __init__(self):
        super().__init__(
            name="planner",
            system_prompt=PLANNER_SYSTEM_PROMPT,
        )

    def create_plan(self, incident: Dict[str, Any]) -> Dict[str, Any]:
        """Create an execution plan for an incident."""
        incident_id = incident.get("incident_id", f"INC-{uuid.uuid4().hex[:6].upper()}")
        logger.info(f"[Planner] Creating plan for {incident_id}: {incident.get('title', '')}")

        # Check for similar past incidents
        vs = get_vector_store()
        search_text = f"{incident.get('title', '')} {incident.get('description', '')}"
        similar = vs.find_similar_incidents(search_text, limit=3, exclude_id=incident_id)

        # Enrich input with similar incidents
        enriched_input = {
            **incident,
            "similar_past_incidents": [
                {
                    "incident_id": s.get("incident_id"),
                    "title": s.get("title"),
                    "root_cause": s.get("root_cause"),
                    "resolution": s.get("resolution"),
                }
                for s in similar
            ] if similar else [],
        }

        # Get plan from LLM
        result = self.run(enriched_input, incident_id)

        # Validate and ensure required fields
        plan = self._validate_plan(result, incident)
        plan["similar_incidents"] = similar or []

        logger.info(f"[Planner] Plan created with {len(plan.get('tasks', []))} tasks")
        return plan

    def _validate_plan(self, raw_plan: Dict, incident: Dict) -> Dict[str, Any]:
        """Validate and fill in missing plan fields."""
        incident_id = incident.get("incident_id", "INC-UNKNOWN")

        # If the LLM returned garbage, build a sensible default plan
        if "tasks" not in raw_plan or not isinstance(raw_plan.get("tasks"), list):
            return self._default_plan(incident)

        plan = {
            "incident_id": raw_plan.get("incident_id", incident_id),
            "severity": raw_plan.get("severity", incident.get("severity", "medium")),
            "initial_assessment": raw_plan.get("initial_assessment", incident.get("title", "")),
            "tasks": raw_plan["tasks"],
            "reasoning": raw_plan.get("reasoning", "Plan generated by Planner Agent"),
        }

        # Ensure each task has required fields
        for task in plan["tasks"]:
            task.setdefault("id", f"t{uuid.uuid4().hex[:4]}")
            task.setdefault("agent", "analyst")
            task.setdefault("input", "")
            task.setdefault("depends_on", [])

        return plan

    def _default_plan(self, incident: Dict) -> Dict[str, Any]:
        """Generate a sensible default plan when LLM output is unusable."""
        incident_id = incident.get("incident_id", "INC-UNKNOWN")
        title = incident.get("title", "Unknown incident")
        description = incident.get("description", "")
        severity = incident.get("severity", "medium")

        return {
            "incident_id": incident_id,
            "severity": severity,
            "initial_assessment": f"Investigating: {title}",
            "tasks": [
                {"id": "t1", "agent": "analyst", "input": f"Analyze logs and metrics for: {title}. {description}", "depends_on": []},
                {"id": "t2", "agent": "researcher", "input": f"Search for similar incidents and known fixes for: {title}", "depends_on": []},
                {"id": "t3", "agent": "coder", "input": f"Write a diagnostic health check script for: {title}", "depends_on": []},
                {"id": "t4", "agent": "communicator", "input": f"Post initial incident update to Slack for {incident_id}: {title} [{severity}]", "depends_on": ["t1"]},
                {"id": "t5", "agent": "executor", "input": f"Create GitHub issue for {incident_id}: {title}", "depends_on": ["t1", "t2"]},
            ],
            "reasoning": "Default plan: analyze logs, research similar incidents, run diagnostics, notify Slack, and create tracking issue.",
        }

    def aggregate_results(self, incident_id: str, plan: Dict,
                          results: Dict[str, Any]) -> Dict[str, Any]:
        """Aggregate worker results into a final resolution summary."""
        logger.info(f"[Planner] Aggregating results for {incident_id}")

        # Build summary from worker results
        analyst_result = results.get("analyst", {})
        researcher_result = results.get("researcher", {})
        executor_result = results.get("executor", {})
        communicator_result = results.get("communicator", {})

        root_cause = analyst_result.get("root_cause", analyst_result.get("result", "Under investigation"))
        confidence = analyst_result.get("confidence", 0.7)

        return {
            "incident_id": incident_id,
            "status": "diagnosed_and_escalated",
            "root_cause": root_cause,
            "confidence": confidence,
            "recommendation": analyst_result.get("recommendation", "Review and remediate"),
            "similar_incidents": plan.get("similar_incidents", []),
            "actions_taken": {
                "github_issue": executor_result,
                "slack_notification": communicator_result,
            },
            "agent_results": results,
            "summary": (
                f"Incident {incident_id} has been diagnosed and escalated. "
                f"Root cause: {root_cause}. "
                f"Confidence: {confidence:.0%}."
            ),
        }
